name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Running tests
      id: running-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Running tests
        setup-command: pip install pytest
        command: pytest 02/
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUNNING-TESTS_RESULTS: "${{steps.running-tests.outputs.result}}"
      with:
        runners: running-tests
